### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by mitch-mitchel**
This PR updates several packages to their latest minor/patch versions to remove security warnings in Miner but also higher up in [Testee](https://github.com/bitovi/testee).

Also updates the `localtunnel` test to use `loca.lt` as `localtunnel.me` is now a proxy that returns generated urls.

### CODE REVIEW

**Comment by mitch-mitchel** [comment]
@daffl Howdy, long time no talk. I see a separate PR for `localtunnel@2.0` but I only tested with the 1.9.x branch. Let me know if I need to tweak anything for this PR. Hope you're well (Mike@bitovi.com)

**Comment by daffl** [comment]
Hi Mike. Should I transfer this repo over to you or Bitovi?

**Comment by mitch-mitchel** [comment]
Bitovi would be best @bmomberger-bitovi what do you think?

**Comment by bmomberger-bitovi** [comment]
I agree. @bitovi should take it.

**Comment by daffl** [comment]
Ok, I invited @mikemitchel to the repo. Once you accept I'll give you admin access so you can transfer it. What username should I add on npm?

**Comment by bmomberger-bitovi** [comment]
My npm user is `bmomberger-bitovi` same as my github user. @mikemitchel is also `mikemitchel` on npm.

**Comment by daffl** [comment]
Ok, both invites sent and added to npm. I don't have access to directly transfer the repository to bitovi but can move it to one of your accounts so you can do the final transfer.

**Comment by bmomberger-bitovi** [comment]
Thanks @daffl! This will be a huge help for maintenance

**Comment by daffl** [comment]
@bmomberger-bitovi If you delete your fork I can transfer this repository to your account.

**Comment by bmomberger-bitovi** [comment]
done-and-done

**Pull request merged**
